# --- Keybinding configuration for Hyprland
#
# See https://wiki.hyprland.org/Configuring/Binds/ for more.

# Example binds, see  for more
bind = $mod, q, killactive
bind = $mod, return, exec, $terminal
bind = Ctrl Alt, Delete, exec, wleave --no-version-info
bind = $mod, Escape, exec, loginctl lock-session
bind = $mod Shift, Escape, exec, systemctl suspend
bind = $mod, e, exec, $fileManager
bind = $mod Shift, f, togglefloating, # move window to/from floating
bind = $mod, f, exec, ~/.config/hypr/scripts/toggle-float-focus.sh
bind = $mod, space, exec, $menu
bind = $mod, w, exec, set-wallpaper

# Move focus with mod + [hjkl]
bind = $mod, h, movefocus, l
bind = $mod, k, movefocus, u
bind = $mod, l, movefocus, r
bind = $mod, j, movefocus, d

# Move focus with mod + shift + [hjkl]
bind = $mod Shift, h, movewindow, l
bind = $mod Shift, k, movewindow, u
bind = $mod Shift, l, movewindow, r
bind = $mod Shift, j, movewindow, d

# Resize active window with mod + ctrl + [hjkl]
binde = $mod Ctrl, h, resizeactive, -20 0
binde = $mod Ctrl, j, resizeactive, 0 20
binde = $mod Ctrl, k, resizeactive, 0 -20
binde = $mod Ctrl, l, resizeactive, 20 0

# Switch workspaces with mod + [1-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9

# Move active window to a workspace with mod + shift + [1-9]
bind = $mod Shift, 1, movetoworkspace, 1
bind = $mod Shift, 2, movetoworkspace, 2
bind = $mod Shift, 3, movetoworkspace, 3
bind = $mod Shift, 4, movetoworkspace, 4
bind = $mod Shift, 5, movetoworkspace, 5
bind = $mod Shift, 6, movetoworkspace, 6
bind = $mod Shift, 7, movetoworkspace, 7
bind = $mod Shift, 8, movetoworkspace, 8
bind = $mod Shift, 9, movetoworkspace, 9

# Move to and open the special workspace
bind = $mod, s, togglespecialworkspace
bind = $mod Shift, s, exec, ~/.config/hypr/scripts/toggle-special-workspace.sh

# Screenshots (clipboard only)
bind = , Print, exec, ~/.config/hypr/scripts/screenshot.sh region
bind = Super, Print, exec, ~/.config/hypr/scripts/screenshot.sh active
bind = Shift, Print, exec, ~/.config/hypr/scripts/screenshot.sh output
bind = Alt, Print, exec, ~/.config/hypr/scripts/screenshot.sh window

# Screenshots (save to disk)
bind = Ctrl, Print, exec, ~/.config/hypr/scripts/screenshot.sh region --save
bind = Super Ctrl, Print, exec, ~/.config/hypr/scripts/screenshot.sh active --save
bind = Ctrl Shift, Print, exec, ~/.config/hypr/scripts/screenshot.sh output --save
bind = Alt Ctrl, Print, exec, ~/.config/hypr/scripts/screenshot.sh window --save

# Move/resize windows with mod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
