vim.pack.add({
  { src = "https://github.com/HiPhish/rainbow-delimiters.nvim" },
  { src = "https://github.com/MunifTanjim/nui.nvim" },
  { src = "https://github.com/NicolasGB/jj.nvim" },
  { src = "https://github.com/OXY2DEV/markview.nvim" },
  { src = "https://github.com/akinsho/toggleterm.nvim" },
  { src = "https://github.com/avm99963/vim-jjdescription" },
  { src = "https://github.com/catppuccin/nvim" },
  { src = "https://github.com/chomosuke/typst-preview.nvim" },
  { src = "https://github.com/echasnovski/mini.nvim" },
  { src = "https://github.com/folke/lazydev.nvim" },
  { src = "https://github.com/folke/which-key.nvim" },
  { src = "https://github.com/igorlfs/nvim-dap-view" },
  { src = "https://github.com/j-hui/fidget.nvim" },
  { src = "https://github.com/jmbuhr/otter.nvim" },
  { src = "https://github.com/julienvincent/hunk.nvim" },
  { src = "https://github.com/justinmk/guh.nvim" },
  { src = "https://github.com/lalitmee/codecompanion-spinners.nvim" },
  { src = "https://github.com/lewis6991/gitsigns.nvim" },
  { src = "https://github.com/lukas-reineke/indent-blankline.nvim" },
  { src = "https://github.com/m4xshen/smartcolumn.nvim" },
  { src = "https://github.com/mfussenegger/nvim-dap" },
  { src = "https://github.com/mikesmithgh/kitty-scrollback.nvim" },
  { src = "https://github.com/mrjones2014/smart-splits.nvim" },
  { src = "https://github.com/neovim/nvim-lspconfig" },
  { src = "https://github.com/nvim-lua/plenary.nvim" },
  { src = "https://github.com/nvim-neotest/nvim-nio" },
  { src = "https://github.com/nvim-telescope/telescope-symbols.nvim" },
  { src = "https://github.com/nvim-telescope/telescope.nvim" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter",             version = "main" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects", version = "main" },
  { src = "https://github.com/olimorris/codecompanion.nvim" },
  { src = "https://github.com/rafamadriz/friendly-snippets" },
  { src = "https://github.com/ravitemer/codecompanion-history.nvim" },
  { src = "https://github.com/ray-x/lsp_signature.nvim" },
  { src = "https://github.com/rcarriga/nvim-notify" },
  { src = "https://github.com/saghen/blink.cmp",                            version = "v1.9.1" },
  { src = "https://github.com/sindrets/diffview.nvim" },
  { src = "https://github.com/stevearc/oil.nvim" },
  { src = "https://github.com/yorickpeterse/nvim-jump" },
})
