vim.pack.add( { "https://github.com/echasnovski/mini.nvim" })

require('mini.ai').setup()
require('mini.align').setup()
require('mini.bracketed').setup()
require('mini.completion').setup()
require('mini.git').setup()
require('mini.icons').setup()
require('mini.indentscope').setup()
require('mini.move').setup()
require('mini.operators').setup()
require('mini.pairs').setup()
require('mini.pick').setup()
require('mini.splitjoin').setup()
require('mini.starter').setup()
require('mini.statusline').setup()
require('mini.surround').setup()
require('mini.tabline').setup()
require('mini.trailspace').setup()

vim.notify = require('mini.notify').make_notify()
