"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sindre Moen"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
pager = ":builtin"

[signing]
backend = "ssh"
behavior = "own"
