# Copy this file over to ./private.toml and edit its values
"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "your@email.addr"

[signing]
key = "/path/to/signing-key.pub"
