"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sindre Moen"

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-formatter = ["difft", "--color", "always", "$left", "$right"]
diff-instructions = false
editor = "nvim"
pager = ":builtin"

[signing]
backend = "ssh"
behavior = "own"

[aliases]
retrunk = ["rebase", "-d", "trunk()"]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[git]
private-commits = "description(glob:'private! *')"
