#!/bin/bash

 # Color directory
CD="$HOME/.Xresources"

# Fetch the Colors
BG=$(cat ${CD} | grep background: | tail -c 8)
FG=$(cat ${CD} | grep foreground: | tail -c 8)

BLACK=$(cat ${CD} | grep color0: | tail -c 8)
RED=$(cat ${CD} | grep color1: | tail -c 8)
GREEN=$(cat ${CD} | grep color2: | tail -c 8)
YELLOW=$(cat ${CD} | grep color3: | tail -c 8)
BLUE=$(cat ${CD} | grep color4: | tail -c 8)
MAGENTA=$(cat ${CD} | grep color5: | tail -c 8)
CYAN=$(cat ${CD} | grep color6: | tail -c 8)
WHITE=$(cat ${CD} | grep color7: | tail -c 8)

# Fonts
FONT="-*-roboto mono-medium-r-*-*-*-*-*-*-*-*-*-uni"

# Panel
PW=1896 # 1920 - 12 * 2
PH=24
PX=12
PY=12

ws(){
	ws=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
	echo "%{F$WHITE}Current workspace: ${ws}"
}

net(){
	ip=$(ip addr show wlp5s0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
	pn=$(timeout .8 ping google.com -c 1 -s 24 | sed '2!d;s/.*time=\([0-9]*\).*/\1/')
	ping=$(if [ -z $pn ] ; then echo "No Connection"; else echo "${pn}ms"; fi)

	echo "%{F$WHITE} ${ip} ${ping}"
}

clock(){
	clock=$(date "+%d %b %Y - %H:%M:%S")
	echo "%{F$WHITE} ${clock}"
}

while :; do
	echo "$(ws)%{c}$(net)%{r}$(clock)"
	sleep .5
done | lemonbar -g ${PW}x${PH}+${PX}+${PY} -f "$FONT" -B "$BG" -F "$FG" -p -d | \
     while :; do read line; eval $line; done &
