# —— Act like GNU screen
# ——————————————————————————————————————————————————————————————————————————————

# Use `Ctrl a` as the prefix
unbind C-b
set -g prefix C-a

# —— Use Vim key bindings
# ——————————————————————————————————————————————————————————————————————————————

setw -g mode-keys vi

# Select panes with the h, j, k and l keys
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Resize panes with the H, J, K and L keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Enter copy mode with ESC
unbind [
bind Escape copy-mode

# Begin visual select with v
bind -T copy-mode-vi 'v' send-keys -X begin-selection

# Yank selected text with y
unbind ]
bind -T copy-mode-vi 'y' send-keys -X copy-selection

# Use p to paste buffer
unbind p
bind p paste-buffer

# —— Pane management
# ——————————————————————————————————————————————————————————————————————————————

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
