# —— Colors
# ——————————————————————————————————————————————————————————————————————————————

# Set the status bar background and foreground to black and white, respectively
set -g status-bg black
set -g status-fg white

# Highlight inactive windows with a dim cyan color
setw -g window-status-bg default
setw -g window-status-fg cyan
setw -g window-status-attr dim

# Highlight active windows with a bright red color
setw -g window-status-current-bg black
setw -g window-status-current-fg red
setw -g window-status-current-attr bright

# Set inactive pane borders in yellow
set -g pane-border-bg black
set -g pane-border-fg yellow

# Highlight active pane borders in green
set -g pane-active-border-bg black
set -g pane-active-border-fg green

# Hightlight the command line with a black background and a bright, white text
set -g message-bg black
set -g message-fg white
set -g message-attr bright
