# —— Tmux plugins
# ——————————————————————————————————————————————————————————————————————————————

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins"

# List plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# Finally, load the plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
