# —— Status bar customization
# ——————————————————————————————————————————————————————————————————————————————

# Increase the possible length of the left part of the status bar
set -g status-left-length 100

# Display session name in gray
set -g status-left "#[fg=colour240]#S"

# Display the date and time. Example: 15.01.2010 » 13:37
set -g status-right "#[fg=magenta]%d.%m.%Y » %H:%M:%S"

# Update the date and time every second
set -g status-interval 1

# Center the window list on the screen
set -g status-justify centre
