source-file ~/.config/tmux/bindings.conf
source-file ~/.config/tmux/colors.conf
source-file ~/.config/tmux/status-bar.conf

# —— Some useful commands
# ——————————————————————————————————————————————————————————————————————————————

# Source configuration file with `Prefix r`
bind r source-file ~/.tmux.conf \; display "Reloaded configuration!"

# Make `Ctrl a` available in other application by pressing it twice
bind C-a send-prefix

# Remap `Prefix c` to always open with same path
bind c new-window -c "#{pane_current_path}"

# —— Miscellaneous configurations
# ——————————————————————————————————————————————————————————————————————————————

# Make tmux recognize zsh as the default
set -g default-command /bin/zsh
set -g default-shell /bin/zsh

# Reduce tmux escape time
set -sg escape-time 0

# Make window indices start on 1 instead of 0
set -g base-index 1

# Make pane indices start on 1 instead of 0
setw -g pane-base-index 1

# Do not allow renaming the window names
set-option -g allow-rename off

# ——————————————————————————————————————————————————————————————————————————————

# Install and source plugins. Keep at bottom.
source-file ~/.config/tmux/plugins.conf
